# This is a basic workflow to help you get started with Actions

name: Deploy FullCalendar with Vue3

on:
  push:
    branches:
      - main  # Set a branch to trigger deployment
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x.x

    - name: Install dependencies
      run: npm install

    - run: npm install -g bats

    - run: bats -v
    
    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Provided by Actions, no need to set it manually
        publish_dir: dist
